### ISSUE TITLE
release_authors[release.get('author').get('login')] -> AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by fearcito** [kulkansecurity/gitxray#4]
Using v1.0.16 and executing `gitxray -r https://github.com/[REDACTED] -f emails -outformat text -out filters.log`

```
Fetching web/releases [Hit CTRL^C to skip]: (57.89%) : 4 seconds left.                              Traceback (most recent call last):
  File "/opt/homebrew/bin/gitxray", line 8, in <module>
    sys.exit(gitxray_cli())
  File "/opt/homebrew/lib/python3.9/site-packages/gitxray/gitxray.py", line 91, in gitxray_cli
    if not repository_xray.run(gx_context, gx_output): continue
  File "/opt/homebrew/lib/python3.9/site-packages/gitxray/xrays/repository_xray.py", line 243, in run
    release_authors[release.get('author').get('login')] += 1
AttributeError: 'str' object has no attribute 'get'
```

**Comment by llavarello** [comment]
@fearcito Thank you for this! I'll commit a fix in a bit and push .2 tomorrow the latest.

**Comment by llavarello** [comment]
@fearcito - Pushed a fix to the repository and to Pypi, creating the release now in GitHub. Closing this Issue, thanks again!
